### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by serra82** [dev26th/bootloader#2]
I would try this bootloader, but I have a lot of error.
I also added -std=c99, this reduce the number of error, but not all.
Can be a problem of toolchain or what else?
thank you

serra82@ubuntu:~/bootloader/bl_f030$ make
mkdir -p build
arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -flto -Wall -Wextra -Wpointer-arith -Wlogical-op -Wfloat-equal -I include -fabi-version=0 -fno-exceptions -Wabi -nostartfiles -Xlinker --gc-sections --specs=nano.specs -T ld/mem.ld -T ld/arm-gcc-link_c.ld -o build/main.elf main.c tiny-AES-c/aes.c && arm-none-eabi-objcopy -O binary build/main.elf build/main.bin && arm-none-eabi-size build/main.elf
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/./cm0-def.h:29:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct Scb_t, SHPR3) == 0x20, "Wrong definition");
               ^
In file included from include/cm0.h:5:0,
                 from include/stm32f030.h:7,
                 from include/stm32f030_f4.h:5,
                 from main.c:5:
include/./cm0-def.h:29:54: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct Scb_t, SHPR3) == 0x20, "Wrong definition");
                                                      ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/./cm0-def.h:48:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct SysTick_t, CALIB) == 0x0C, "Wrong definition");
               ^
In file included from include/cm0.h:5:0,
                 from include/stm32f030.h:7,
                 from include/stm32f030_f4.h:5,
                 from main.c:5:
include/./cm0-def.h:48:58: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct SysTick_t, CALIB) == 0x0C, "Wrong definition");
                                                          ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/./cm0-def.h:68:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct Nvic_t, IPR[0]) == 0x0300, "Wrong definition");
               ^
In file included from include/cm0.h:5:0,
                 from include/stm32f030.h:7,
                 from include/stm32f030_f4.h:5,
                 from main.c:5:
include/./cm0-def.h:68:58: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct Nvic_t, IPR[0]) == 0x0300, "Wrong definition");
                                                          ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:65:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct CRC_t, INIT) == 0x10, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:65:53: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct CRC_t, INIT) == 0x10, "Wrong definition");
                                                     ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:87:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct PWR_t, CSR) == 0x04, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:87:52: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct PWR_t, CSR) == 0x04, "Wrong definition");
                                                    ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:122:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct RCC_t, CR2) == 0x34, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:122:52: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct RCC_t, CR2) == 0x34, "Wrong definition");
                                                    ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:314:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct GPIO_t, BRR) == 0x28, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:314:53: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct GPIO_t, BRR) == 0x28, "Wrong definition");
                                                     ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:675:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct SYSCFG_t, CFGR2) == 0x18, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:675:57: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct SYSCFG_t, CFGR2) == 0x18, "Wrong definition");
                                                         ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:810:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct EXTI_t, PR) == 0x14, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:810:52: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct EXTI_t, PR) == 0x14, "Wrong definition");
                                                    ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:987:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct DMA_t, channels[4].CMAR) == 0x64, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:987:65: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct DMA_t, channels[4].CMAR) == 0x64, "Wrong definition");
                                                                 ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1080:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct ADC_t, CHSELR) == 0x0028, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1080:57: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct ADC_t, CHSELR) == 0x0028, "Wrong definition");
                                                         ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1081:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct ADC_t, DR)     == 0x0040, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1081:57: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct ADC_t, DR)     == 0x0040, "Wrong definition");
                                                         ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1082:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct ADC_t, CCR)    == 0x0308, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1082:57: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct ADC_t, CCR)    == 0x0308, "Wrong definition");
                                                         ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1210:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct TIM_t, DMAR) == 0x4C, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1210:53: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct TIM_t, DMAR) == 0x4C, "Wrong definition");
                                                     ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1454:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct RTC_t, ALRMASSR) == 0x44, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1454:57: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct RTC_t, ALRMASSR) == 0x44, "Wrong definition");
                                                         ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1583:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct IWDG_t, WINR) == 0x10, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1583:54: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct IWDG_t, WINR) == 0x10, "Wrong definition");
                                                      ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1604:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct WWDG_t, SR) == 0x08, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1604:52: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct WWDG_t, SR) == 0x08, "Wrong definition");
                                                    ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1651:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct USB_t, CNTR) == 0x40, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1651:53: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct USB_t, CNTR) == 0x40, "Wrong definition");
                                                     ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1652:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct USB_t, BCDR) == 0x58, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1652:53: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct USB_t, BCDR) == 0x58, "Wrong definition");
                                                     ^
include/stm32f030.h:1671:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(union UsbBuf_t) == 16, "Wrong definition");
               ^
include/stm32f030.h:1671:45: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(union UsbBuf_t) == 16, "Wrong definition");
                                             ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1776:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct SPI_t, TXCRCR) == 0x18, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1776:55: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct SPI_t, TXCRCR) == 0x18, "Wrong definition");
                                                       ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1840:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct I2C_t, TXDR) == 0x28, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1840:53: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct I2C_t, TXDR) == 0x28, "Wrong definition");
                                                     ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:1949:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct USART_t, TDR) == 0x28, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:1949:54: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct USART_t, TDR) == 0x28, "Wrong definition");
                                                      ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:2051:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct DBGMCU_t, CR) == 0x04, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:2051:54: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct DBGMCU_t, CR) == 0x04, "Wrong definition");
                                                      ^
In file included from /usr/include/newlib/string.h:17:0,
                 from main.c:3:
include/stm32f030.h:2069:15: error: expected declaration specifiers or '...' before '__builtin_offsetof'
 static_assert(offsetof(struct FLASH_t, WRPR) == 0x20, "Wrong definition");
               ^
In file included from include/stm32f030_f4.h:5:0,
                 from main.c:5:
include/stm32f030.h:2069:55: error: expected declaration specifiers or '...' before string constant
 static_assert(offsetof(struct FLASH_t, WRPR) == 0x20, "Wrong definition");
                                                       ^
In file included from main.c:6:0:
include/startup-common.h: In function 'Reset_Handler':
include/startup-common.h:30:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for(uint32_t *t = &_sdata, *f = &_sidata; t < &_edata; ++t, ++f) *t = *f;
     ^
include/startup-common.h:30:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
include/startup-common.h:33:19: error: redefinition of 't'
     for(uint32_t *t = &_sbss; t < &_ebss; ++t) *t = 0;
                   ^
include/startup-common.h:30:19: note: previous definition of 't' was here
     for(uint32_t *t = &_sdata, *f = &_sidata; t < &_edata; ++t, ++f) *t = *f;
                   ^
include/startup-common.h:33:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for(uint32_t *t = &_sbss; t < &_ebss; ++t) *t = 0;
     ^
In file included from main.c:7:0:
include/isr/stm32f030.h: At top level:
include/isr/stm32f030.h:70:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(g_IRQHandlers) == (0x00BC + sizeof(g_IRQHandlers[0])), "Wrong ISR vector size");
               ^
include/isr/stm32f030.h:70:77: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(g_IRQHandlers) == (0x00BC + sizeof(g_IRQHandlers[0])), "Wrong ISR vector size");
                                                                             ^
include/isr/stm32f030.h:71:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(g_IRQHandlers)/sizeof(g_IRQHandlers[0]) == (16 + 1 + USB_IRQn), "Wrong ISR vector size");
               ^
include/isr/stm32f030.h:71:86: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(g_IRQHandlers)/sizeof(g_IRQHandlers[0]) == (16 + 1 + USB_IRQn), "Wrong ISR vector size");
                                                                                      ^
main.c:65:15: error: expected declaration specifiers or '...' before 'sizeof'
 static_assert(sizeof(struct StartData) <= sizeof(buf), "Data too big");
               ^
main.c:65:56: error: expected declaration specifiers or '...' before string constant
 static_assert(sizeof(struct StartData) <= sizeof(buf), "Data too big");
                                                        ^
main.c: In function 'revU32':
main.c:77:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for(size_t i = 0; i < 32; ++i) {
     ^
main.c: In function 'CRC_addByte':
main.c:90:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for(uint8_t pos = 0x01; pos; pos <<= 1) {
     ^
main.c: In function 'doStart':
main.c:315:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for(uint32_t a = APP_START; a < APP_END; a += PAGE_SIZE)
     ^
tiny-AES-c/aes.c: In function 'AES_CBC_decrypt_buffer':
tiny-AES-c/aes.c:418:3: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
   for (uint32_t i = 0; i < length; i += BLOCKLEN)
   ^
tiny-AES-c/aes.c:418:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by serra82** [comment]
I resolved the problem adding: -std=gnu11 into Makefile

**Comment by dev26th** [comment]
The Makefile is tested with gcc 7.2.1. With this version the "-std=gnu11" is not required.
